# Generated by Django 3.2.5 on 2021-08-07 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node', to='socials.instagram')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='node', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('success', 'Success'), ('error', 'Error')], default='info', max_length=22)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('S', 'Sent'), ('D', 'Delivered'), ('R', 'Read')], default='S', max_length=10)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='nodes.node')),
            ],
        ),
    ]
