# Generated by Django 3.2.5 on 2021-08-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instagrampost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=25, unique=True)),
                ('title', models.TextField(blank=True)),
                ('embed_src', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='feeds/instagram')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
