# Generated by Django 3.2.5 on 2021-08-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_instagrampost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instagrampost',
            options={'verbose_name': 'Instagram Post'},
        ),
        migrations.AlterModelOptions(
            name='youtubechannel',
            options={'verbose_name': 'Youtube Channel'},
        ),
        migrations.AlterModelOptions(
            name='youtubekeyword',
            options={'verbose_name': 'Youtube Keyword'},
        ),
        migrations.AlterModelOptions(
            name='youtubeplaylist',
            options={'verbose_name': 'Youtube Playlist'},
        ),
        migrations.AlterModelOptions(
            name='youtubetag',
            options={'verbose_name': 'Youtube Tag'},
        ),
        migrations.AlterModelOptions(
            name='youtubevideo',
            options={'verbose_name': 'Youtube Video'},
        ),
    ]
