# Generated by Django 3.2.5 on 2021-08-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0005_auto_20210813_1743'),
        ('feeds', '0003_auto_20210809_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='viewers',
            field=models.ManyToManyField(blank=True, null=True, related_name='viewed_instagram_posts', to='nodes.Node'),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='viewers',
            field=models.ManyToManyField(blank=True, null=True, related_name='viewed_youtube_videos', to='nodes.Node'),
        ),
    ]
