# Generated by Django 3.2.5 on 2021-08-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('userid', models.IntegerField()),
                ('bio', models.TextField(null=True)),
                ('dp', models.ImageField(blank=True, null=True, upload_to='instagram')),
                ('link', models.URLField(null=True)),
                ('verified', models.BooleanField()),
                ('private', models.BooleanField()),
            ],
        ),
    ]
