# Generated by Django 3.2.5 on 2021-07-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('userid', models.IntegerField()),
                ('bio', models.TextField()),
                ('dp', models.URLField()),
                ('link', models.URLField()),
                ('verified', models.BooleanField()),
                ('private', models.BooleanField()),
            ],
        ),
    ]
