# Generated by Django 3.2.5 on 2021-08-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0002_auto_20210808_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instagramprofile',
            options={'verbose_name': 'Instagram  Profile'},
        ),
        migrations.RemoveField(
            model_name='instagramprofile',
            name='is_authenticated',
        ),
        migrations.AddField(
            model_name='instagramprofile',
            name='followed_back',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instagramprofile',
            name='is_followed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instagramprofile',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instagramprofile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
