# Generated by Django 3.2.5 on 2021-07-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0002_auto_20210722_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagram',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='instagram',
            name='dp',
            field=models.ImageField(blank=True, null=True, upload_to='instagram'),
        ),
    ]
