# Generated by Django 3.2.5 on 2021-08-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_remove_node_instagram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('href', models.URLField(blank=True, null=True)),
                ('onclick', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='action',
            field=models.ManyToManyField(blank=True, related_name='_nodes_notification_action_+', to='nodes.Action'),
        ),
    ]
