# Generated by Django 3.2.5 on 2021-07-21 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0004_auto_20210721_0430'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialNodes',
        ),
    ]
