# Generated by Django 3.2.5 on 2021-08-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0004_auto_20210812_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='actions',
        ),
        migrations.AddField(
            model_name='notification',
            name='action',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='href',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='onclick',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Action',
        ),
    ]
