# Generated by Django 3.2.5 on 2021-07-22 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0002_auto_20210722_1419'),
        ('nodes', '0005_delete_socialnodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='node',
            name='twitter',
        ),
        migrations.AlterField(
            model_name='node',
            name='instagram',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node', to='socials.instagram'),
        ),
    ]
