# Generated by Django 3.2.5 on 2021-07-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0007_alter_notification_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='level',
            field=models.CharField(default='info', max_length=22),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(default='sent', max_length=10),
        ),
    ]
